#!/usr/bin/python3

import sys

# 入力
def main():
    value = []
    for line in sys.stdin:
        line = line.strip()

local_max = []
local_min = []

# 順番
for i in range(1, len(value) -1):
    pre_value = value[i - 1]
    now_value = value[i]
    next_value = value[i + 1]

    #大小を確認
    if now_value > pre_value and now_value > next_value:
        local_max.append(now_value)
    else now_value < pre_value and now_value < next_value:
        local_min.append(now_value)