#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 highbrige-yayoi <hainu738@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

# 入力
def main():
    value = []
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            value.append(int(line))
        except ValueError:
            continue

    # print(f"--- 読み込み完了: {len(value)} 個のデータ ---")

    local_max = []
    local_min = []

    # 順番
    for i in range(1, len(value) -1):
        pre_value = value[i - 1]
        now_value = value[i]
        next_value = value[i + 1]

        #大小を確認
        if now_value > pre_value and now_value > next_value:
            local_max.append(now_value)

        if now_value < pre_value and now_value < next_value:
            local_min.append(now_value)


    for x in local_max:
        print(x)
    
    print()

    for x in local_min:
        print(x)

if __name__ == "__main__":
    main()